### ISSUE TITLE
Create buttons component

### ISSUE THREAD

**Issue by Dishebh** [creativecommons/vue-vocabulary#222]
**Description**

Create buttons component, similar to what is present in vocabulary.

**Want to take up?**

[Yes]

**Comment by Dishebh** [comment]
@dhruvkb please let me know if it is a valid issue, and if I can work upon it. Thanks!

**Comment by dhruvkb** [comment]
Hi @Dishebh we have planned not to create components for the very simple elements (like buttons and inputs) because they are about the same effort to write as adding classes to pure HTML elements, while adding maintenance cost. You should read the [Overview document](https://cc-vocabulary.netlify.app/?path=/docs/vocabulary-overview--page#principle-2).

A large-sized primary-coloured button in HTML:
```html
<button class="button is-primary is-large">HTML button</button>
```
A large-sized primary-colored button in Vue.js:
```vue
<Button size="large" is-primary>Vue.js</Button>
<!-- And that's not counting the whole definition of the Button, 
which adds maintenance effort. -->
```
